Feature/task 5 10_main_page
team-1507/super_game pull request #4
Opened 2022-07-14 21:01 UTC by Anastasia226

2022-07-15 11:10 UTC, Alex-KY requested changes

2022-07-15 11:10 UTC, Alex-KY commented on src/app/App.scss
> +.ant-btn-primary{
```suggestion
.ant-btn-primary {
```
Наверное, приятнее читать с отступом

2022-07-15 11:10 UTC, Alex-KY commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
Считаю именовать иконки нужно более конкретно, потому что стрелок у нас ещё может быть какое-то количество.. или задать параметр на направление..
Но конкретно здесь, на мой взгляд, иконка должна называться ArrowComeIn или ArrowTopRight.

2022-07-15 11:10 UTC, Alex-KY commented on src/pages/home-page/home-page.scss
> +            @include font-style($font-size: 150px,$letter-spacing: -0.06em,$font-family: UbuntuCondensed);
```suggestion
            @include font-style($font-size: 150px, $letter-spacing: -0.06em, $font-family: UbuntuCondensed);
```
Кстати, мы не будем чётко определять единицы, в которых будем работать? А то я вижу прям чуть ли не все)
Ну и отступы бы)

2022-07-15 11:21 UTC, Anastasia226 commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
ну добавлять одну и ту же иконку в разных направлениях как по мне не стоит, так как можно стилями ее покрутить

2022-07-15 11:21 UTC, Anastasia226 commented on src/pages/home-page/home-page.scss
> +            @include font-style($font-size: 150px,$letter-spacing: -0.06em,$font-family: UbuntuCondensed);
все единицы брала с фигмы, поэтму так) а с отступами что?

2022-07-15 11:23 UTC, Alex-KY commented on src/pages/home-page/home-page.scss
> +            @include font-style($font-size: 150px,$letter-spacing: -0.06em,$font-family: UbuntuCondensed);
пробелы в смысле, то есть, то нет) Мб в stylelint прописать просто и залинтфиксить

2022-07-15 11:24 UTC, Anastasia226 commented on src/pages/home-page/home-page.scss
> +            @include font-style($font-size: 150px,$letter-spacing: -0.06em,$font-family: UbuntuCondensed);
а окей, поправлю

2022-07-15 11:25 UTC, Alex-KY commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
![image](https://user-images.githubusercontent.com/23631014/179214211-fec1f594-1f65-4f7b-aa12-9206e97a2c7d.png)
То есть мы за основу берём такую стрелку и будем её вращать?)

2022-07-15 11:28 UTC, Anastasia226 commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
ну можно повернуть направо и ее уже вращать)

2022-07-15 11:31 UTC, Alex-KY commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
![image](https://user-images.githubusercontent.com/23631014/179214976-458d74fb-a216-46e6-8a4d-534449d0b3a8.png)
![image](https://user-images.githubusercontent.com/23631014/179215080-a9b8fe1f-5485-4507-be83-69f719719429.png)

Хм, но я пока не увидел таких же перевёрнутых.. они все разные)

2022-07-15 11:36 UTC, Alex-KY commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
Надо с Кириллом переболтать.. 
@sincerely-manny может основные стрелки подгоним под один формат.. чтобы можно было их вращать..

2022-07-15 11:39 UTC, Anastasia226 commented on src/components/icons/Arrow.tsx
> +const Arrow = () => {
ну да кстати, я этого не учла) переименную тогда

2022-07-15 19:49 UTC, Alex-KY approved these changes
ок =)

2022-07-15 23:52 UTC, sincerely-manny approved these changes
Лед тронулся!☺️

2022-07-17 20:50 UTC, walborn approved these changes

2022-07-17 20:50 UTC, walborn commented on src/components/icons/ArrowTopRight.tsx
> +export default ArrowTopRight;
🧐 Можно импортировать svg как компонент (см. https://blog.logrocket.com/how-to-use-svgs-in-react/)

2022-07-18 19:05 UTC, merged